module.exports=(sequelize,DataTypes)=>{
    const Designer=sequelize.define('designer',{
        designername:{
            type:DataTypes.STRING,
            allowNull:false
        },
        active:{
            type:DataTypes.BOOLEAN
        },
        mailID:{
            type:DataTypes.STRING,
            allowNull:false
        },
        age:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        designerid:{
            type:DataTypes.INTEGER,
            
        },
        gender:{
            type:DataTypes.STRING,
            allowNull:false
        },
        address:{
            type:DataTypes.STRING,
            allowNull:false
        },
        phonenumber:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        password:{
            type:DataTypes.STRING,
            allowNull:false
        },
        designerid:{
            type:DataTypes.INTEGER
        }
    })
    return Designer
}