module.exports=(sequelize,DataTypes)=>{
    const Order=sequelize.define('userorder',{
        userid:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        orderid:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        NumberofItems:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        productid:{
            type:DataTypes.INTEGER,
        },
        orderdate:{
            type:DataTypes.DATE,
            allowNull:false
        },
        description:{
            type:DataTypes.STRING,
            allowNull:false
        },
        des_cont_num:{
            type:DataTypes.BIGINT,
            allowNull:false
        },
        des_name:{
            type:DataTypes.STRING,
            allowNull:false
        },
        des_id:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        
        ownproduct:{
            type:DataTypes.BOOLEAN,
            allowNull:false
        },
        amt_to_pay:{
            type:DataTypes.FLOAT
        },
        orderstatus:{
            type:DataTypes.STRING,
            allowNull:false
        },
        paid_amount:{
            type:DataTypes.FLOAT
        },
        paymentid:{
            type:DataTypes.STRING,
        },
        tentativedate:{
            type:DataTypes.DATE
        },
        imagepath:{
            type:DataTypes.STRING,
            allowNull:false
        },
        shipmentdate:{
            type:DataTypes.DATE
        }
    })
    return Order
}